#! /bin/env python

import cubi.engine as engine
import cubi.logger as logger
import cubi.utils as utils
from cubi.engine import Servant


class SimpleServant(Servant):

    def hello(self, params):
        return dict(params)


if __name__ == '__main__':
    # product logger level
    # log = logger.get_console_logger(logging.DEBUG)
    # logger.set_logger(log)

    # deubg logger level
    logger.enable_debug_log()

    endp = 'simple-server@0.0.0.0:2018'
    setting = {}
    setting['debug'] = True
    setting['endpoint'] = endp
    utils.make_easy_engine(SimpleServant, setting).serve_forever()
